#!/bin/sh
nb=100
layer="input"
out="generated/$layer"
dataset=B

for v in model*.pkl; do
    echo $v
    mkdir -p "$out/$v"
    for k in 1 2 3; do
        echo $k
        invoke check --dataset="$dataset" --what=genetic --filename=$v --opname=random --out="$out/$v/random-$k-x.png" --params="{\"k\": $k, \"nb\": $nb}" --layer-name="$layer"
    done
    invoke check --dataset="$dataset" --what=genetic --filename=$v --opname=crossover --out="$out/$v/crossover.png" --params="{\"nb\": $nb}" --layer-name="$layer"
    

    for a in 0.8 0.1 0.5 0.9; do
        for b in 0.99999 0.9999 0.99999 0.999; do
           echo "a=$a b=$b"
           invoke check --dataset="$dataset" --what=genetic --filename=$v --opname=mutation --out="$out/$v/mutation-a$a-b$b-x.png" --params="{\"a\": $a, \"b\": $b, \"nb\": $nb}" --layer-name=$layer
        done
    done
done
