#!/bin/sh
F1="g#stats.out_of_the_box_classification.m2.objectness"
lightjob show --fields="summary,where,content.model_name,g#summary,$F1,readable_end_time,content.model_params.nb_layers" --sort=$F1 --state=success --type=training --details --descending --where=jobset83
