#!/bin/sh
F="g#stats.out_of_the_box_classification.letterness.diversity_count_letters_85"
lightjob show --fields="summary,where,content.model_name,g#summary,g#stats.out_of_the_box_classification.letterness.sample_objectness,$F" --sort=$F --state=success --type=training --details --descending
