#!/bin/sh
V="
diversity_count_digits_85
diversity_count_digits_90
diversity_count_digits_95
diversity_count_digits_98
diversity_count_digits_99
diversity_count_digits_999
diversity_max_digits
"
for v in $V;do 
    python tools/viz/obox.py --field="stats.out_of_the_box_classification.letterness.$v" --model-folder=tools/models/mnist/m2 --out='exported_data/figs/obox/{field}/{summary}.png' --name="letterness|$v" --nb=10 $*
done
V="
objectness
"
for v in $V;do 
    python tools/viz/obox.py --field="stats.out_of_the_box_classification.fonts.$v" --model-folder=tools/models/mnist/m2 --out='exported_data/figs/obox/{field}/{summary}.png' --name='letter_objectness' --nb=10 $*
done
